from adsorption import *
from mpmath import mp

precision = mp.dps = 30 # Represent number with 50 digits precision, necessary 
            # to avoid numerical problems when dealing with differences 
	    # between small numbers generated by exponentials

assert precision>=30, AssertionError( "You need high precision to avoid numerical problem, set to 50" )

# This is really just for bookkeeping, basically decide the units to be used 
nm = 1.0 # 1 nm in units of length
nm2 = nm*nm # 1 nm^2 in units of area
nm3 = nm*nm*nm # 1 nm^3 in units of volume
mm = 1e6 * nm # 1 mm in units of length
mm3 = mm**3 # 1 mm^3 in units of volume
L = 1e24 * nm3 # 1 L in units of volume
mL = 1e-3 * L # 1 mL in units of volume
um = 1.0e3 * nm # 1 micrometer
um2 = um*um # 1 um^2 in units of area
kT = 1.0 # 1 kT in units of energy
g = 1.0 # 1 g is units of mass, only for bookkeeping

# Define derived units
L = 1e24 * nm3 # 1 L in units of volume
M = 6.023e23 / L # Avogadro's number 
nM = M * 1e-9 # 1 nM 

#****Dosing particles intravenously to animal******
Npdosing=8e12 / mL # Number of particles in dosing solution per mL [mL-1]
Vdosing=5*0.02 * mL # Dosing volume for each animal [mL] (e.g. 5 mL/kg and animal weight 0.02 kg)
fTzone=0.1 # Fraction of dosed particles that ends up in T zone of animal spleen
VTzone=0.5*0.084 * mL # Volume of spleen Tzone in animal [mL] (Assuming 50% of mouse spleen of volume 0.084 mL)
NP_conc=Npdosing*Vdosing*fTzone/VTzone # Number of particles per mL in Tzone of mouse spleen [mL-1]

# Define the design of the multivalent nanoparticle
def Nmonomers( MW ):
    '''Calculate the number of monomers in a PEG chain of a given molecular weight'''
    return int( MW - 18 ) / 44.0

NmonoLong = Nmonomers( 3400 * g ) # Number of monomers in PEG3400 chain
NmonoShort = Nmonomers( 2000 * g ) # Number of monomers in PEG3400 chain
amono = 0.28 * nm # Monomer size in PEG chain
PEG2K = np.sqrt( NmonoShort ) * amono # Extension of the short PEG chain
PEG_max_extension = NmonoLong * amono # Max extension of the long PEG to which ligands are attached
KD = 1.0 * nM # Dissociation constant in solution between ligand-receptor
K_bind_0 = KD**(-1) # Binding constant in solution between ligand-receptor
R_NP = 35 * nm # Nanoparticle radius in units of length
A1 = np.pi / 3.0 
A2 = (( R_NP + PEG_max_extension) ** 2 - ( R_NP + PEG2K) ** 2 ) * ( R_NP + PEG2K ) 
A3 = - 2.0 * R_NP ** 3 * ( 1.0 - (R_NP + PEG2K) / (R_NP + PEG_max_extension))
v_bind = A1 * ( A2 + A3 ) 
N_ligands = 150 # Number of ligands on the nanoparticle
sigma_L = 150.0 / ( 4.0 * np.pi * R_NP**2 ) # surface density of ligands
sigma_P2K = 1.0 / ( 2.0 * nm )**2  # Surface density of short PEG chains

data_polymers = {}
data_polymers['short'] = {"N": NmonoShort, "a": amono, "sigma": sigma_P2K, "name" : "PEG2K" }
data_polymers['ligands'] = {"N": NmonoLong, "a": amono, "sigma": sigma_L, "name":"ligands" }

# Define system parameters - this info should be checked, for now it is just
# a search from chatGPT
N_lympho = 7.5e7 # Average number of lymphocytes in mouse spleen
N_T_cells = 0.25 * N_lympho # Number of T cells in mouse spleen
V_spleen = 100 * mm3 # Volume of mouse spleen
cell_conc = N_T_cells / V_spleen # T cell concentration in the spleen
A_cell = 100 * um2 # Cell area 
sigma_R_min = 1.0 / um2 # Minimum receptor surface density.
                        # Corresponds to average distance between receptors is 1 um
sigma_R_max = 1e4 / um2 # Maximum receptor surface density
                        # Corresponds to average distance between receptors is 10 nm

# Control output
verbose = False
n_sampling_points = 50 #Number of sampling points for the receptor surface density

# Create the system
system = MultivalentBinding( kT=kT, R_NP = R_NP, 
                            data_polymers=data_polymers, 
                            binding_model = "saddle", 
                            polymer_model = "gaussian",
                            A_cell = A_cell, 
                            NP_conc = NP_conc, 
                            cell_conc = cell_conc, )
 
# Store everything in a file, so we can plot it later
with open( 'adsorption.dat', 'w+' ) as f:
    min_exp = np.log10( sigma_R_min )
    max_exp = np.log10( sigma_R_max )
    M_conc = (A_cell/(np.pi * R_NP**2)) * cell_conc # Concentration of binding sites for NPs
    print( f'NP concentration {NP_conc/(1/mL):5.3e} (1/mL)' )
    print( f'Binding sites concentration {M_conc/(1/mL):5.3e} (1/mL)' )
    print( f'Max adsorbed fraction achievable: min(1, M_conc/NP_conc) = {min(1, M_conc/NP_conc):5.3e}' )
    f.write( f'sigma_R (um^-2) KD_eff (M) adsorbed_fraction\n' )
    for sigma_R in np.logspace( min_exp, max_exp, n_sampling_points ):
        K_bind = system.calculate_binding_constant( 
                                                          K_bind_0=K_bind_0, 
                                                          sigma_R = sigma_R, 
                                                          verbose = verbose)
        
        print( f'Effective dissociation constant (M): {float((1.0 / K_bind) / M):5.3e}' )
        # Now we can calculate the adsorbed fraction
        adsorbed_fraction = system.calculate_bound_fraction( K_bind=K_bind )
        # Print the adsorbed fraction
        out1 = float(sigma_R/(1/um2))
        out2 = float((1 / K_bind) / M)
        out3 = float(adsorbed_fraction)
        f.write( f"""{out1:5.3e} {out2:5.3e} {out3:5.3e}\n""")
        print( f'Adsorbed fraction, ideal polymer: {out3:5.3e}' )
        print( "------------------" )

# Now we can plot the results
import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt( 'adsorption.dat', skiprows=2 )
plt.xscale( 'log' )
plt.yscale( 'linear' )
plt.plot( data[:,0], data[:,2], linestyle='solid' )
plt.xlabel( 'Receptor surface density $(\mu$m$^{-2}$)' )
plt.ylabel( 'Adsorbed fraction' )
plt.legend()
plt.savefig( 'adsorption.png' )
plt.close()

