from adsorption import *
from units import *
from system_variables_test import *
from mpmath import mp

precision = mp.dps = 50 # Represent number with 50 digits precision, necessary 
            # to avoid numerical problems when dealing with differences 
	    # between small numbers generated by exponentials

assert precision>=30, AssertionError( "You need high precision to avoid numerical problem, set to 50" )

# Control output
verbose = False
n_sampling_points = 50 #Number of sampling points for the receptor surface density

# These two parameters simply control the maximum and minimum receptor surface density
# for which calculations are made
sigma_R_min = 1.0 / um2 # Minimum receptor surface density.
                        # Corresponds to average distance between receptors is 1 um
sigma_R_max = 1e4 / um2 # Maximum receptor surface density
                        # Corresponds to average distance between receptors is 10 nm
NP_area = R_NP**2 * np.pi

depletion = True

# Create the system
system = MultivalentBinding( kT=kT, R_NP = R_NP, 
                            data_polymers=data_polymers, 
                            binding_model = "exact", 
                            polymer_model = "gaussian",
                            A_cell = A_SPR, 
                            NP_conc = NP_conc, 
                            cell_conc = 1/V_SPR, )
 
# Store everything in a file, so we can plot it later
with open( 'adsorption.dat', 'w+' ) as f:
    min_exp = np.log10( sigma_R_min )
    max_exp = np.log10( sigma_R_max )
    M_conc = (A_SPR/(np.pi * R_NP**2)) / V_SPR # Concentration of binding sites for NPs
    sigma_R_values = np.logspace( min_exp, max_exp, n_sampling_points )
    
    K_bind_vs_receptors = None
    for i, sigma_R in enumerate(sigma_R_values):
        #print(f"Step {i}, sigma {sigma_R}")
        bound_fraction, K_i = system.calculate_bound_fraction_with_fluctuations_correct(
                                K_bind_0,
                                sigma_R, 
                                K_bind_vs_receptors,
                                max_n_receptor = 200,
                                NP_conc = NP_conc,
                                rho_m = M_conc,
                                )
        K_bind_vs_receptors = K_i
                            
    
        # Print the adsorbed fraction
        out1 = float(sigma_R/(1/um2))
        #out2 = float((1 / K_bind_vs_receptors[i]) / M)
        out3 = float(bound_fraction)
        if depletion:
            out4 = float(bound_fraction) * NP_conc
        else:
            out4 = float(bound_fraction) * (A_cell/NP_area)

        #f.write( f"""{out1:5.3e} {out2:5.3e} {out3:5.3e} {out4:5.3e}\n""")
        #print( f"""{out1:5.3e} {out2:5.3e} {out3:5.3e} {out4:5.3e}\n""")
        f.write( f"""{out1:5.3e} {out3:5.3e} {out4:5.3e}\n""")
        print( f"""{out1:5.3e} {out3:5.3e} {out4:5.3e}\n""")
        
        #f.write( f"""{out1:5.3e}  {out3:5.3e}\n""")
        #print( f'Adsorbed fraction, ideal polymer: {out3:5.3e}' )
        #print( "------------------" )

# Now we can plot the results
import matplotlib.pyplot as plt
import numpy as np

data = np.loadtxt( 'adsorption.dat', skiprows=2 )
plt.xscale( 'log' )
plt.yscale( 'linear' )
plt.plot( data[:,0], data[:,2], linestyle='solid' )
#plt.plot( data[:,0], data[:,1], linestyle='solid' )
plt.xlabel( 'Receptor surface density $(\mu$m$^{-2}$)' )
plt.ylabel( 'Adsorbed fraction' )
plt.legend()
plt.savefig( 'adsorption.png' )
plt.close()
